### PR TITLE
Consolidate Durability and export for use in queries

### PR DESCRIPTION
**Pull request by cotrone**
This should fix issue #65.

### CODE REVIEW

**Comment by codedmart** [comment]
@cotrone The failures appear to be separate from your changes. I will take a look soon. Thanks for the pr.

**Comment by AtnNn** [comment]
These changes LGTM

**Comment by codedmart** [comment]
@AtnNn Sorry I should have mentioned that they look good. I was referring to looking at the failures soon since I will be upping the bounds for aeson as well for stack.

**Comment by codedmart** [comment]
Internet is a little laggy today. Thanks @cotrone 👍

**Comment by cotrone** [comment]
Sorry for the mess of commits! Probably would have been better as separate PRs. The CI build isn't passing though.

**Comment by codedmart** [comment]
@cotrone Sorry been pretty busy. I pulled your PR and it seems to pass all tests locally so I will try to look into why travis is failing today or tomorrow and get this wrapped up. Thanks! cc @AtnNn

**Comment by AtnNn** [comment]
It looks like `master` is also [failing on Travis](https://travis-ci.org/AtnNn/haskell-rethinkdb/builds/144443825) because of a deprecation warning from what seems like the `network` library.

**Comment by codedmart** [comment]
@AtnNn Right, but that deprecation warning is not present on this PR. As in @cotrone did a fix for it: https://github.com/AtnNn/haskell-rethinkdb/pull/66/files#diff-f4426d89377eb4a9e3b8e3b64bfddb92L29. I haven't had a chance to look at this yet, but it does build and tests pass for me locally.

**Comment by codedmart** [comment]
Closed in 88479d21f56d1ef772d8cb3a3c89d1d2259cc83a

**Pull request closed without merging**
