### PR TITLE
Update travis config (dependency cache)

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by codedmart** [comment]
@phadej thanks for the PR. Looks like from the failures this could be related to PR #62. I will take a look tomorrow.

**Comment by codedmart** [comment]
I just merged #62 if you want to rebase. Thanks!

**Comment by phadej** [comment]
Rebased

**Comment by phadej** [comment]
Seems that `doctests` are broken (require some service to exist?), also `7.6` build doesn't work, as ultimately `doctest` depens on `ghc` which depends on `bytestring`, and newer one than bundled is  required somewhere :(

**Comment by codedmart** [comment]
@phadej sorry didn't look at the changes in detail before. Not sure about 7.6, but you removed the before_script install/setup of rethinkdb.

**Comment by phadej** [comment]
@codedmart I see, it would make life easier if you try to get rethinkdb whitelisted on travis: https://github.com/travis-ci/apt-source-whitelist

**Comment by phadej** [comment]
Disabled benchmark building on `GHC-7.6` which made things green.

**Comment by codedmart** [comment]
@phadej Looks good, thanks! I am not a travis expert so the whitelist is a great suggestion. I appreciate it.

**Pull request merged**
